### ISSUE TITLE
Automate package releases

### ISSUE THREAD

**Issue by dvalters** [BritishGeologicalSurvey/etlhelper#14]
Configure Travis to automatically push new tags to PyPI as releases.

**Comment by volcan01010** [comment]
The pipeline code is merged now and the bugs that failed the build are fixed (#21).  However, the deployment fails.  This is due to the name of the package that is created by setup.py (etlhelper-unknown0.zip).  It seems like the `package` stage of the CI isn't picking out the tags somehow.

If you have a look in the GitLab CI history, you can see what I mean.

**Comment by dvalters** [comment]
Ah OK, I will take a look at what's going on

**Comment by volcan01010** [comment]
Adding Git to the container has allowed Versioneer to get the version, however the build is registering as dirty.  See pipelines on `packaging-fix` branch in GitLab.
