### ISSUE TITLE
Provide pyproject.toml for pip install

### ISSUE THREAD

**Issue by ximenesuk** [BritishGeologicalSurvey/etlhelper#158]
When pip installing from a github branch this deprecation warning is given:
> DEPRECATION: etlhelper is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at [https://github.com/pypa/pip/issues/8559]( https://github.com/pypa/pip/issues/8559

## To Do

- [x] Should we include an optional dependency argument for `pkg`?
- [x] Update build documentation in `CONTRIBUTING.md`?
- [x] Should we add extra authors to `pyproject.toml`?
- [x] Should we remove `requirements.txt`? If so, update `README` and `CONTRIBUTING` documentation for requirements installation.
- [x] Should we remove `versioneer`? If so, add replacement to set `__version__`.
- [x] Remove all `versioneer` files
- [x] Update the `Dockerfile` to use the new `pyproject.toml` file

**Comment by leorudczenko** [comment]
The `pyproject.toml` file should reflect the newest changes to `setup.py` from pull request #151

**Comment by leorudczenko** [comment]
I've been testing `pyproject.toml` on another project and have now added a `toml` file to this repository. Below is a description I've created of the new build process we can follow:



## Package Distribution

### Required Libraries

- `build`
- `twine`

An additional optional dependency could be added to the `toml` file as `pkg`, which would include the distribution requirements. This currently has **NOT** been done, but can be added.

```bash
pip install .[pkg]
```

### Build and Upload

First, you will need to create a new git release. You should only do this after all commits for the release have been made.

**Once you have created a new release, ensure you pull the newest tag matching that release locally before building local distributions.** _This is because `setuptools_scm` uses the latest git tag versioning to update the dynamic version in the `pyproject.toml` config file during the build._

Then, you need to build the distribution files:

```bash
python -m build
```

Then you can upload the distribution of the library to PyPI:

```bash
twine upload dist/*
```

If you encounter the error `File already exists`, this is because you have likely an older version locally in your `dist/` directory. To work around this, run:

```bash
twine upload --skip-existing dist/*
```

You can also just specify the exact build files you wish to upload:

```bash
twine upload dist/etlhelper-0.14.2*
```

You will then be prompted to login with your username and password. Alternatively, you can authenticate using an API token:

```bash
Enter your username: __token__
Enter your password: ******
```

**Note:** _When using an API token, your username should be `__token__` and your password should be your API token._

### Extras

#### Authors

We could add multiple authors in the `toml` file so that it matches the `README.md` file. This currently has **NOT** been done, but can be added.

#### Requirements

`requirements.txt` my not be required after the `toml` file inclusion. See this discussion here for detailed information: https://github.com/pypa/pip/issues/8049

#### Versioneer

`versioneer` is now not needed for the build stage. However, it is still currently used to set the `__version__`  attribute of the package in `etlhelper/__init__.py`. 

We may be able to remove `versioneer` if desired: https://stackoverflow.com/questions/5581722/how-can-i-rewrite-python-version-with-git

#### Row factory submodule

Currently, `etlhelper.row_factories` is accessed directly from `etlhelper/row_factories.py`, it is not imported in any `__init__` files. Whilst the submodule is accessible, code editors (e.g., VSCode) cannot provide productivity improvements for this submodule:

![image](https://github.com/BritishGeologicalSurvey/etlhelper/assets/116461518/e2f54023-0edf-4a04-826a-cf30255c9438)

To solve this, we could:
- Add `from etlhelper import row_factories` to `etlhelper/__init__.py`

## To Do

- [ ] Should we include an optional dependency argument for `pkg`?
- [ ] Should we add build documentation to `README`?
- [ ] Should we add extra authors to `pyproject.toml`?
- [ ] Should we remove `requirements.txt`? If so, update `README` documentation for requirements installation.
- [ ] Should we remove `versioneer`? If so, add replacement to set `__version__`.
- [ ] Fix `etlhelper.row_factories` import for code editors.

**Comment by volcan01010** [comment]
We will need to update the Dockerfile to build using the new `.toml` file.  While we are here, we should update to a Python 3.9 base container and update the internal CI files to use a more recent Docker-in-Docker.

**Comment by leorudczenko** [comment]
Regarding the current debate around using `versioneer`, I've found a post on stackoverflow with a much simpler method for assigning `__version__` in package distribution: https://stackoverflow.com/a/56984285

```python
from pkg_resources import (
    get_distribution,
    DistributionNotFound,
)

try:
    __version__ = get_distribution(__name__).version
except DistributionNotFound:
    pass
```

I have tested this on my test package and it works just fine using the current git tags setup. It also does not require any library installation because `pkg_resources` is built-in.

**Comment by volcan01010** [comment]
This has been done and merged into `for_v1`
